
#pragma once

// Do not edit this file it is generated by generate-eventnames so your changes will be lost!

typedef enum {
  EVENT_NONE = 0,
  EVENT_ENC_BTN = 1,
  EVENT_ENC_A = 2,
  EVENT_ENC_B = 3,
  EVENT_STOP = 4,
  EVENT_Y_MIN = 5,
  EVENT_X_MIN = 6,
  EVENT_X_MAX = 7,
  EVENT_X_AT_MIN = 8,
  EVENT_MOTOR_ERROR = 9,
  EVENT_RUNNING = 10,
  EVENT_TEST = 11,


  EVENTS_USED,
  EVENT_ACTIVE = 128,
} Event;
